/*
 * The configuration's shape, in one place.
 *
 * Three things are derived from what is written here: the parse every
 * configuration is admitted by, the TypeScript types the application reads
 * configuration through, and the references an operator writes their
 * configuration from — `env.example`, `portal.config.example.json` and the
 * JSON Schema `portal.config.schema.json`, all generated by
 * `pnpm config:generate`. Adding a setting means adding it here and
 * regenerating, rather than writing it into a type, a check and reference files
 * that are free to disagree.
 *
 * A `describe()` string is operator-facing: it is what the generated references
 * carry beside the setting. Where one names another setting, it names the
 * variable rather than the key, since the variable is the spelling an operator
 * types and the one a JSON file's key is easy to read off.
 *
 * The configuration arrives as environment variables, assembled into the nested
 * document this schema describes by ./env, which maps
 * `PORTAL_TENANT_ACME_OAUTH_GOOGLE_CLIENT_ID` onto
 * `tenants.acme.oauth.google.clientId`, and as portal.config*.json files, read
 * by ./files, which hold that document as it is. Keys here stay camelCase for
 * the application's sake and the files'; the mapping is what spells them for
 * the environment.
 */

import path from 'path';

import {z} from 'zod';

import {getMaxConnections, mailAccountKey} from '@/notification/mail-account';
import {isReservedSegment, reservedSegments} from '@/path/reserved-segments';
import {filesystemRoot, objectPrefix} from '@/storage/paths';
import {
  DEFAULT_PART_SIZE,
  MAX_PART_SIZE,
  MIN_PART_SIZE,
} from '@/storage/s3-limits';
import {canonicalHost} from '@/tenant/routing';

import {envNameFor, TENANTS_KEY} from './names';

/*
 * A tenant id is the URL path segment the tenant is served under, and the
 * segment of every variable that configures it.
 *
 * Lowercase letters and digits only, opening with a letter. The environment
 * decides most of that: a variable name is uppercased and split on underscores,
 * so an id holding either would never round-trip, and a hyphen cannot be typed
 * into a shell's `export`. The leading letter is what the proxy also demands of
 * a first segment before it will read it as a tenant name, so an id without one
 * would be configured and then never routed to. The proxy's own pattern is
 * wider, and an id it matches that this refuses resolves no tenant, which is
 * the right answer.
 */
const TENANT_ID_PATTERN = /^[a-z][a-z0-9]*$/;

/* Reserving the whole width a payment context id can reach: a Hub PISP payment
 * carries `${contextId}-${tenantId}` in a field of 35 characters, and a context
 * id is a bigint sequence, so its 19 digits and the separator leave 15. */
const TENANT_ID_MAX_LENGTH = 15;

/*
 * A positive whole number.
 *
 * Rejected at load rather than corrected at the point of use: a setting
 * silently replaced by a default is how a deployment ends up believing it set
 * three and running at ten.
 */
const positiveInteger = () => z.int().min(1);

/*
 * The hostnames the auth library's own host check accepts: DNS labels of at
 * most 63 characters, an IPv4 literal (which those labels already cover), or a
 * bracketed IPv6 literal. An underscore is the character that occurs in
 * practice and is not among them.
 */
const HOSTNAME_PATTERN =
  /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*|\[[0-9a-fA-F:]+\])$/;

/*
 * Whether a value is an origin this deployment can be reached at, spelled the
 * way an origin is spelled.
 *
 * Exactness matters because nothing parses the value again. Absolute addresses
 * are built by concatenating onto it, so anything trailing the host survives into
 * them: a lone trailing slash emails `<host>//auth/reset-password/…`, which
 * matches no tenant and no reserved segment, so the proxy answers not-found.
 * Stored workspace addresses are matched by string prefix against it, so a
 * spelling that differs from the canonical one — a default port written out, an
 * uppercase host — matches none of them and the tenant resolves no workspace.
 *
 * Refused rather than corrected to the canonical spelling, because this value is
 * typed into AOS as well, as the prefix of every workspace address held there.
 * Repairing only the copy here would leave the two disagreeing.
 *
 * The host is restricted to what the auth library accepts, because one it
 * refuses is resolved from the request URL by the request handler and from the
 * configured origin by a server-side session read. An OAuth redirect address
 * built under the first is not the one registered under the second, and the
 * identity provider refuses it.
 */
function isDeploymentOrigin(value: string): boolean {
  return parseOrigin(value) !== null;
}

/* The parsed form of an origin, or null for a value that is not one. Callers
 * that need to read a part of it go through this rather than `new URL`, which
 * throws — and a throw raised while the configuration is being checked escapes
 * the parse, so a mistyped origin would be reported as an unhandled TypeError
 * naming neither the variable nor the tenant. */
function parseOrigin(value: unknown): URL | null {
  if (typeof value !== 'string') return null;

  let url: URL;

  try {
    url = new URL(value);
  } catch {
    return null;
  }

  /* An origin holds a scheme and a host and can hold nothing else, so equality
   * with the parsed origin settles the trailing characters and the canonical
   * spelling at once. It settles nothing about the scheme: `ftp://`, `ws://` and
   * `wss://` each parse to an origin equal to what was written, so the protocol
   * test beside it is what admits only the two a deployment is served over.
   *
   * Ports 80 and 443 are refused however they are written. A scheme's own port
   * fails the equality (`new URL` leaves it off the origin), and the crossed
   * spellings — https on 80, http on 443 — parse but can never be reached: a
   * Host header carries no scheme, so request routing treats both ports as
   * default and would strip what the configuration declared. */
  const isOrigin =
    (url.protocol === 'http:' || url.protocol === 'https:') &&
    value === url.origin &&
    url.port !== '80' &&
    url.port !== '443' &&
    HOSTNAME_PATTERN.test(url.hostname);

  return isOrigin ? url : null;
}

const ORIGIN_ERROR =
  'must be written as an origin — a scheme and a host, with no path, query, ' +
  'fragment or trailing slash, e.g. https://portal.example.com. Ports 80 and ' +
  '443 are the defaults and are left off';

// The variable carrying a setting, for descriptions and messages.
const name = envNameFor;

/**
 * What the browser is handed about a tenant.
 *
 * Membership in this group is what marks a value as safe to send to a browser:
 * everything here reaches every visitor's page, and nothing outside it does.
 * Groups mirror the server-side ones they pair with — `paypal` beside
 * `payments.paypal`, `webPush.publicKey` beside `webPush.privateKey` — so the
 * two halves of one credential are found under one name.
 */
const publicConfigSchema = z
  .strictObject({
    host: z
      .string()
      .min(1)
      .refine(isDeploymentOrigin, {error: ORIGIN_ERROR})
      .describe(
        `Origin this tenant is served on, e.g. https://portal.example.com — scheme and host only, with no trailing slash. Workspace URLs are stored against it, every absolute link is built from it, and the deployment trusts it as an origin to authenticate on, so a tenant without one resolves no workspace. Tenants sharing an origin is the ordinary case; the scheme must be the one ${name(['origin'])} carries.`,
      ),
    paypal: z
      .strictObject({
        clientId: z
          .string()
          .min(1)
          .describe(
            "The PayPal client id the browser's checkout button is created with. Public by design; the secret stays in the payments group.",
          ),
      })
      .optional(),
    webPush: z
      .strictObject({
        publicKey: z
          .string()
          .min(1)
          .describe(
            `The VAPID public key a browser subscribes with. Pairs with ${name([TENANTS_KEY, '<id>', 'webPush', 'privateKey'])}; both are needed for notifications.`,
          ),
      })
      .optional(),
    mattermost: z
      .strictObject({
        host: z
          .string()
          .min(1)
          .describe('Mattermost address the sidebar links to.'),
      })
      .optional(),
    keycloak: z
      .strictObject({
        buttonLabel: z
          .string()
          .describe(
            'Text of the Keycloak sign-in button; defaults to "Log In with Keycloak".',
          )
          .optional(),
        buttonImage: z
          .string()
          .describe(
            'Address of the image shown on the Keycloak sign-in button; defaults to the bundled Keycloak mark.',
          )
          .optional(),
      })
      .optional(),
    links: z
      .strictObject({
        linkedin: z.string().optional(),
        twitter: z.string().optional(),
        instagram: z.string().optional(),
        whatsapp: z.string().optional(),
      })
      .describe('Social addresses the news application offers to share to.')
      .optional(),
  })
  .describe(
    'Browser-facing settings for this tenant. Everything in this group is sent to every visitor; nothing outside it is.',
  );

const aosAuthSchema = z
  .strictObject({
    apiKey: z.string().optional(),
    username: z.string().optional(),
    password: z.string().optional(),
  })
  .refine(auth => !!auth.apiKey || !!(auth.username && auth.password), {
    error: 'requires an API key, or a username and a password',
  })
  .describe(
    'AOS credentials: an API key (AOS 9+, generated in AOS under Preferences → API Keys), or a username and password for basic auth. The API key wins when both are set.',
  );

/*
 * The store a tenant's files live in — the one its AOS instance is configured
 * with, since the two applications read and write the same files.
 *
 * Laid out as AOP lays out its own settings: a switch naming the provider, and
 * a group of settings per provider beside it. Written that way rather than as
 * one shape per provider because the environment spells a setting as a path of
 * keys, so every provider's settings have to sit under a key of their own for
 * a variable to name them. Adding a provider is a value in the enum and a
 * group beside the others; the store implementations are registered in
 * lib/core/storage.
 */
const filesystemStorageSchema = z
  .strictObject({
    dir: z
      .string()
      .min(1)
      .describe(
        `The AOS instance's data.upload.dir base path (created on first connect; back it with a mounted volume so uploads survive). When ${name([TENANTS_KEY, '<id>', 'aos', 'tenantId'])} is set — a tenant on a shared multi-tenant AOS instance — the portal reads and writes files under <dir>/<tenantId> to match AOP's per-tenant subdirectory; a dedicated instance uses this path as-is.`,
      ),
  })
  .describe(
    'The AOS instance keeps its files on a filesystem the portal can reach: its data.upload.dir, mounted into the portal at the path given here.',
  );

const s3StorageSchema = z
  .strictObject({
    endpoint: z
      .string()
      .min(1)
      .describe(
        'Address of the service, scheme included, e.g. https://minio.example.com:9000 — the value of data.object-storage.endpoint with its scheme. Leave unset for AWS S3 itself, which the region names.',
      )
      .optional(),
    region: z
      .string()
      .min(1)
      .describe(
        "Region the requests are signed for. AWS S3 requires the bucket's own; a service outside AWS accepts any value, and us-east-1 is used when unset.",
      )
      .optional(),
    bucket: z
      .string()
      .min(1)
      .describe(
        'The bucket, as data.object-storage.bucket names it. It has to exist already: the portal does not create it, and checks it is reachable when the tenant connects, which needs the s3:ListBucket permission besides the object permissions.',
      ),
    accessKey: z
      .string()
      .min(1)
      .describe(
        `Access key of the account, set together with ${name([TENANTS_KEY, '<id>', 'aos', 'storage', 's3', 'secretKey'])}. Leave both unset to let the client find credentials on its own — the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY variables, a shared credentials file, or the role of the machine the portal runs on.`,
      )
      .optional(),
    secretKey: z
      .string()
      .min(1)
      .describe('Secret key going with the access key.')
      .optional(),
    pathStyle: z
      .boolean()
      .describe(
        'Address an object as <endpoint>/<bucket>/<key> rather than <bucket>.<endpoint>/<key> — data.object-storage.path-style. Most services outside AWS need true. Defaults to false.',
      )
      .optional(),
    encryption: z
      .enum(['SSE-S3', 'SSE-KMS'])
      .describe(
        `Server-side encryption asked for on every upload, as data.object-storage.encryption spells it: SSE-S3 for keys the service manages, SSE-KMS for a key of your own named by ${name([TENANTS_KEY, '<id>', 'aos', 'storage', 's3', 'kmsKeyId'])}. Unset leaves the bucket's own default in force.`,
      )
      .optional(),
    kmsKeyId: z
      .string()
      .min(1)
      .describe(
        'The KMS key encrypting uploads — data.object-storage.encryption-kms-key-id. Read only with SSE-KMS.',
      )
      .optional(),
    storageClass: z
      .string()
      .min(1)
      .describe(
        "Storage class every upload is written with, e.g. STANDARD or STANDARD_IA — data.object-storage.storage-class. Unset leaves the bucket's default.",
      )
      .optional(),
    partSize: z
      .int()
      .min(MIN_PART_SIZE)
      .max(MAX_PART_SIZE)
      .default(DEFAULT_PART_SIZE)
      .describe(
        `Bytes every part but the last carries when a file reaches the bucket part by part. The S3 API takes no less than ${MIN_PART_SIZE} (5 MiB) and no more than ${MAX_PART_SIZE} (5 GiB); defaults to ${DEFAULT_PART_SIZE} (16 MiB). Larger parts mean fewer requests to the bucket and more bytes held on local disk while one is gathered; smaller parts the reverse. A file that never fills a part is stored in one request once it is whole.`,
      ),
  })
  .describe(
    `The AOS instance keeps its files in an S3-compatible bucket, configured by its data.object-storage.* settings; the same values go here. When ${name([TENANTS_KEY, '<id>', 'aos', 'tenantId'])} is set — a tenant on a shared multi-tenant AOS instance — every key is put behind <tenantId>/ to match AOP's per-tenant prefix; a dedicated instance writes keys as they are.`,
  );

const storageProviderSchema = z.enum(['filesystem', 's3']);

export type StorageProvider = z.infer<typeof storageProviderSchema>;

const storageSchema = z
  .strictObject({
    provider: storageProviderSchema.describe(
      `Where this tenant's files are kept — the same place its AOS instance keeps them. "filesystem" reads and writes the instance's data.upload.dir, configured under ${name([TENANTS_KEY, '<id>', 'aos', 'storage', 'filesystem'])}_…; "s3" reads and writes the bucket its data.object-storage.* settings name, configured under ${name([TENANTS_KEY, '<id>', 'aos', 'storage', 's3'])}_….`,
    ),
    filesystem: filesystemStorageSchema.optional(),
    s3: s3StorageSchema.optional(),
  })
  /* Settled into one shape per provider, so the application reads the settings
   * of the provider that was chosen and no other. The group the provider names
   * is required, and only that group is kept: a group left over from a
   * previous choice is refused rather than ignored, since leaving it in place
   * is how a deployment ends up believing it moved its files and did not. */
  .transform((storage, ctx) => {
    const kept: Record<string, unknown> = {provider: storage.provider};

    for (const provider of storageProviderSchema.options) {
      const settings = storage[provider];

      if (provider === storage.provider) {
        if (!settings) {
          ctx.addIssue({
            code: 'custom',
            path: [provider],
            message: `is required when ${name([TENANTS_KEY, '<id>', 'aos', 'storage', 'provider'])} is ${provider}`,
          });
        }
        kept[provider] = settings;
      } else if (settings) {
        ctx.addIssue({
          code: 'custom',
          path: [provider],
          message: `is set while ${name([TENANTS_KEY, '<id>', 'aos', 'storage', 'provider'])} is ${storage.provider}; remove it, or change the provider`,
        });
      }
    }

    if (storage.s3 && !!storage.s3.accessKey !== !!storage.s3.secretKey) {
      ctx.addIssue({
        code: 'custom',
        path: ['s3', storage.s3.accessKey ? 'secretKey' : 'accessKey'],
        message:
          'is required: the access key and the secret key are set together',
      });
    }

    if (storage.s3?.kmsKeyId && storage.s3.encryption !== 'SSE-KMS') {
      ctx.addIssue({
        code: 'custom',
        path: ['s3', 'kmsKeyId'],
        message: `is read only when ${name([TENANTS_KEY, '<id>', 'aos', 'storage', 's3', 'encryption'])} is SSE-KMS`,
      });
    }

    return kept as
      | {
          provider: 'filesystem';
          filesystem: z.output<typeof filesystemStorageSchema>;
        }
      | {provider: 's3'; s3: z.output<typeof s3StorageSchema>};
  });

const aosSchema = z.strictObject({
  url: z
    .string()
    .min(1)
    .describe(
      'Base URL of the AOS instance, e.g. https://erp.example.com/axelor-erp. Unique per tenant when each tenant has a dedicated AOS instance; the same for every tenant sharing one multi-tenant AOS instance.',
    ),
  tenantId: z
    .string()
    .describe(
      'AOS-side tenant id — independent of the portal tenant id. Set it when this tenant lives on a shared AOS instance with AOS multi-tenancy: every AOS call then carries X-Tenant-ID with this value, and files are read and written under the subdirectory or key prefix AOP gives that tenant. Leave unset for a dedicated AOS instance.',
    )
    .optional(),
  storage: storageSchema,
  auth: aosAuthSchema,
  webhookSecret: z
    .string()
    .describe(
      'Secret AOS uses to sign notification webhooks for this tenant. Set the same value in the AOS portal configuration.',
    )
    .optional(),
});

const paymentsSchema = z
  .strictObject({
    paypal: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        live: z
          .boolean()
          .describe('true for live payments; defaults to sandbox.')
          .optional(),
        webhookId: z
          .string()
          .min(1)
          .describe(
            'Id of the webhook registered for this tenant in the PayPal developer dashboard. PayPal signs each notification, and the signature is checked against this id. Without it, PayPal notifications are refused and a payment is recorded only when the buyer comes back to the site.',
          )
          .optional(),
      })
      .describe(
        `PayPal merchant account. The browser needs the client id as well, under ${name([TENANTS_KEY, '<id>', 'public', 'paypal', 'clientId'])}.`,
      )
      .optional(),
    stripe: z
      .strictObject({
        clientSecret: z.string().min(1),
        bankTransferCountry: z
          .string()
          .length(2)
          .describe(
            'Two-letter country whose bank account Stripe presents for EUR bank transfers; defaults to FR.',
          )
          .optional(),
        webhookSecret: z
          .string()
          .describe(
            "Stripe webhook signing secret for this tenant's webhook endpoint. Without it, bank transfer is not offered at checkout.",
          )
          .optional(),
      })
      .optional(),
    paybox: z
      .strictObject({
        site: z.string().min(1),
        rang: z.string().min(1),
        identifiant: z.string().min(1),
        secret: z.string().min(1),
        paybox: z.string().min(1).describe('Paybox payment page base URL.'),
        backup1: z.string().optional(),
        backup2: z.string().optional(),
      })
      .optional(),
    up2pay: z
      .strictObject({
        site: z.string().min(1),
        rang: z.string().min(1),
        identifiant: z.string().min(1),
        secret: z.string().min(1),
        paybox: z.string().min(1).describe('Up2Pay payment page base URL.'),
        legacyForwardUrl: z
          .string()
          .describe(
            'Where to forward Up2Pay IPNs this tenant cannot attribute to a portal payment (legacy-ERP invoices, unknown context). Omit to not forward.',
          )
          .optional(),
      })
      .optional(),
    hubpisp: z
      .strictObject({
        tokenUrl: z.string().min(1),
        apiUrl: z.string().min(1),
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        certFingerprint: z.string().min(1),
        beneficiaryName: z
          .string()
          .min(1)
          .max(70)
          .describe(
            'Name of the account a payment is credited to, at most 70 characters — the ISO 20022 limit for a creditor name. The value is sent as it stands, with nothing truncating it on the way out.',
          ),
        iban: z.string().min(1),
        bic: z.string().optional(),
        certsDir: z
          .string()
          .min(1)
          .describe(
            "Directory holding this tenant's mTLS client.crt and private-key.pem. Must be distinct per Hub PISP tenant — the certificate is the tenant's bank identity, so there is no shared default.",
          ),
      })
      .describe(
        "Hub PISP (BPCE) account. Register this tenant's webhook under this tenant's own path — /<tenantId>/api/webhooks/hubpisp/..., without the <tenantId> segment for a tenant reached on an origin of its own — so the webhook uses this tenant's credentials.",
      )
      .optional(),
  })
  .describe(
    'Per-tenant merchant accounts. A provider a tenant omits is simply unavailable for that tenant.',
  );

const mailSchema = z
  .strictObject({
    host: z.string().min(1),
    port: positiveInteger()
      .max(65535)
      .describe(
        'TCP port the SMTP server listens on, commonly 587 for STARTTLS or 465 with secure set.',
      ),
    secure: z.boolean().optional(),
    user: z.string().min(1),
    password: z.string().min(1),
    email: z.string().describe('From address; defaults to user.').optional(),
    maxConnections: positiveInteger()
      .describe(
        "Connections this tenant's mail account may hold open at once. A mail server limits concurrency per sender, so the ceiling belongs to the account — a Microsoft 365 mailbox allows three. Tenants sharing a mailbox share one pool and one ceiling, so they must agree on this value or the configuration is refused at startup. Defaults to 10.",
      )
      .optional(),
  })
  .describe('Per-tenant SMTP settings.');

const oauthSchema = z
  .strictObject({
    google: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
      })
      .optional(),
    keycloak: z
      .strictObject({
        clientId: z.string().min(1),
        clientSecret: z.string().min(1),
        issuer: z
          .string()
          .min(1)
          .describe(
            'Keycloak realm issuer URL, with or without a trailing slash. Each tenant uses its own realm.',
          )
          /* A trailing slash and no trailing slash are two spellings of the same
           * issuer and both correct. Settled to one of them so the discovery
           * address built from it is well-formed either way: the doubled slash
           * the other spelling produces resolves to no discovery document, which
           * is read as a sign-in starts, so the tenant's Keycloak sign-in fails
           * before the visitor reaches the realm at all. A value that is not
           * another spelling of the same issuer but a mistake — no scheme, or an
           * issuer already ending in the discovery path — is left to fail rather
           * than repaired. */
          .transform(issuer => issuer.replace(/\/+$/, '')),
      })
      .optional(),
  })
  .describe(
    "Per-tenant OAuth applications. Each provider is registered under the provider id '<provider>-<tenantId>' — register the matching redirect URI (/<tenantId>/api/auth/oauth2/callback/<provider>-<tenantId>, without the <tenantId> segment for a tenant reached on an origin of its own) with the identity provider. There is no global app: a tenant offers a provider only when it declares it here.",
  );

export const tenantConfigSchema = z.strictObject({
  sessionSecret: z
    .string()
    .min(1)
    .describe(
      "Signing and encryption secret for this tenant's sessions. Per tenant, not per deployment: each tenant authenticates through an instance of its own, so a secret that leaks forges sessions for that tenant alone. Generate a distinct long random value for every tenant (openssl rand -base64 32) — two tenants sharing one are refused.",
    ),
  routing: z
    .enum(['path', 'host'])
    .describe(
      `How this tenant's addresses are shaped. "path" (the default) carries the tenant id as the first path segment, e.g. https://portal.example.com/acme/sales, and the origin may be shared with other tenants. "host" drops that segment and lets ${name([TENANTS_KEY, '<id>', 'public', 'host'])} name the tenant instead, e.g. https://acme.example.com/sales. "host" needs a host no other tenant is served on, and a proxy that sets X-Forwarded-Host (or Host) to the address the visitor used rather than the address of the server behind it — nginx sends its own upstream address by default, and a deployment left that way resolves no tenant and refuses every form submission. Changing this changes every address the tenant is reached at: the stored workspace URLs, the registered OAuth redirect URIs and the links already sent out all carry the old shape.`,
    )
    .optional(),
  includeLanguage: z
    .boolean()
    .describe(
      "Also load the base language (e.g. 'en' for 'en-US') in addition to the specific locale. Defaults to false.",
    )
    .optional(),
  db: z.strictObject({
    url: z
      .string()
      .min(1)
      .describe(
        "Postgres connection URL of this tenant's own database. Every tenant has its own database; isolation is per-database.",
      ),
  }),
  aos: aosSchema,
  payments: paymentsSchema.optional(),
  mail: mailSchema.optional(),
  mattermost: z
    .strictObject({
      token: z.string().describe('Mattermost admin token.').optional(),
      createUsers: z
        .boolean()
        .describe('Create Mattermost users on registration.')
        .optional(),
    })
    .describe(
      `Mattermost integration. The address the browser links to is browser-facing and lives under ${name([TENANTS_KEY, '<id>', 'public', 'mattermost', 'host'])}.`,
    )
    .optional(),
  oauth: oauthSchema.optional(),
  webPush: z
    .strictObject({
      privateKey: z.string().min(1),
      subject: z
        .string()
        .min(1)
        .describe(
          'mailto: address or https: URL identifying the sender to push services.',
        ),
    })
    .describe(
      `Web-push signing identity; the public key lives under ${name([TENANTS_KEY, '<id>', 'public', 'webPush', 'publicKey'])}. The service worker registers once per tenant — under the tenant path segment where several tenants share an origin, and at the root of the origin where the tenant has one to itself — so each tenant holds its own push subscription and its own key pair takes effect either way.`,
    )
    .optional(),
  upload: z
    .strictObject({
      recordRetentionHours: z
        .number()
        .describe(
          'How long terminal staged-upload records are kept before the prune sweep deletes them. Defaults to 168 (7 days).',
        )
        .optional(),
    })
    .optional(),
  public: publicConfigSchema,
});

/**
 * The settings bound to the single process rather than to a tenant.
 */
export const deploymentConfigSchema = z.strictObject({
  origin: z
    .string()
    .min(1)
    .refine(isDeploymentOrigin, {error: ORIGIN_ERROR})
    .describe(
      `Origin serving the addresses that name no tenant — "/" and the deployment's own routes under /deployment — e.g. https://portal.example.com, scheme and host only with no trailing slash. Every tenant's own origin (${name([TENANTS_KEY, '<id>', 'public', 'host'])}) is trusted for authentication alongside it, and a request arriving on a host none of them names is answered under this one. Its scheme decides whether the deployment's session cookies are written as __Secure-, so every origin in the configuration has to share it.`,
    ),
  defaultTenant: z
    .string()
    .min(1)
    .describe(
      'Tenant serving the addresses that name none of their own: "/", and a script run with no --tenant. Must name a configured tenant. A deployment configuring one tenant leaves this out — that tenant is the only answer and is filled in. Beyond one it is required as soon as any tenant is reached under a path segment, since "/" on the origin such a tenant is served on names no tenant. A deployment whose tenants are all reached by host may leave it out; each tenant then answers "/" on the origin it holds, a script needs --tenant, and "/" on the deployment\'s own origin answers not-found unless a tenant holds that host too.',
    )
    .optional(),
  push: z
    .strictObject({
      maxConnections: positiveInteger()
        .describe(
          'Push deliveries in flight at once, and sockets held per push service. One agent serves the whole process, so this bounds the deployment. Defaults to 10.',
        )
        .optional(),
    })
    .optional(),
  imageCache: z
    .strictObject({
      maxBytes: positiveInteger()
        .describe(
          "Bytes the resized-image cache may occupy. One cache directory serves every tenant, so the budget is the deployment's.",
        )
        .optional(),
    })
    .optional(),
  upload: z
    .strictObject({
      tempDir: z
        .string()
        .min(1)
        .describe(
          "Directory a tenant using object storage stages an upload in, under one subdirectory per tenant; it holds at most one part per upload in flight. A tenant on a filesystem stages in its own storage directory and ignores this. Defaults to <temp>/portal/uploads under the operating system's temporary directory. Point it at a volume that survives a restart to let an interrupted upload resume from the exact byte it reached rather than the last whole part.",
        )
        .optional(),
    })
    .optional(),
});

export type TenantConfig = z.output<typeof tenantConfigSchema>;
export type DeploymentConfig = z.output<typeof deploymentConfigSchema>;

/** What the browser is handed about a tenant: the `public` group, parsed. */
export type PublicConfig = TenantConfig['public'];

/* The shapes as they are written, before the parse settles the storage settings
 * into one shape per provider and the Keycloak issuer's trailing slash. Anything
 * that writes a configuration builds these rather than the parsed shapes, so a
 * value it emits is one an operator could have typed. Giving a setting a default
 * or a coercion parts the two further, so a writer must never reach for the
 * parsed shapes instead. */
export type TenantConfigInput = z.input<typeof tenantConfigSchema>;
export type DeploymentConfigInput = z.input<typeof deploymentConfigSchema>;

type TenantEntry = [string, TenantConfig];

/* A violated configuration-wide invariant, reported against the setting that
 * has to change rather than against the configuration as a whole. */
type ConfigIssue = {path: string[]; message: string};

const tenantPath = (id: string, ...keys: string[]) => [
  TENANTS_KEY,
  id,
  ...keys,
];

/* Cross-tenant invariant. A Hub PISP tenant authenticates to BPCE with an mTLS
 * client certificate loaded from its certsDir (client.crt + private-key.pem) —
 * that certificate is the tenant's enrolled bank identity, so two tenants must
 * never resolve to the same certsDir or they would transact as the same bank
 * client. certsDir is required per tenant, so this only has to reject two
 * tenants that point at the same directory. Paths are resolved to absolute so
 * equivalent specs (relative vs absolute, trailing slash) compare equal. */
function checkHubPispCertIsolation(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const byCertsDir = new Map<string, string>(); // resolved certsDir -> tenant id

  for (const [id, config] of tenants) {
    const configured = config.payments?.hubpisp?.certsDir;
    if (!configured) continue;

    const certsDir = path.resolve(configured);
    const owner = byCertsDir.get(certsDir);

    if (owner) {
      issues.push({
        path: tenantPath(id, 'payments', 'hubpisp', 'certsDir'),
        message:
          `Tenants "${owner}" and "${id}" share the same HUB PISP certsDir ` +
          `("${certsDir}"). Each HUB PISP tenant needs its own mTLS client ` +
          `certificate — give each a directory of its own.`,
      });
      continue;
    }

    byCertsDir.set(certsDir, id);
  }

  return issues;
}

/*
 * Where a tenant's files sit, as the store will place them: the directory a
 * filesystem tenant resolves to, or the bucket and prefix an object-storage
 * tenant writes under. Spelled so that one root containing another reads as a
 * prefix of it — a directory ends in a separator, a bucket prefix in the slash
 * every key of it opens with — so a plain string comparison settles nesting.
 */
function storageRoot(config: TenantConfig): {
  setting: string[];
  root: string;
} {
  const {storage, tenantId} = config.aos;

  if (storage.provider === 's3') {
    const {endpoint, bucket} = storage.s3;

    /* Two spellings of one service — a trailing slash, a capital in the host —
     * name the same bucket, so the endpoint is compared as the origin it
     * parses to; one that does not parse is compared as written, and none at
     * all means AWS itself. */
    const service =
      endpoint === undefined
        ? 'aws'
        : URL.canParse(endpoint)
          ? new URL(endpoint).origin.toLowerCase()
          : endpoint;

    return {
      setting: ['aos', 'storage', 's3', 'bucket'],
      root: `${service}/${bucket}/${objectPrefix(tenantId)}`,
    };
  }

  return {
    setting: ['aos', 'storage', 'filesystem', 'dir'],
    root: filesystemRoot(storage.filesystem.dir, tenantId) + path.sep,
  };
}

/* Cross-tenant invariant. Uploads are recorded as a key relative to the tenant's
 * part of its store, so two tenants resolving to the same part share one
 * namespace: each would resolve the other's recorded keys, and the retention
 * sweep would delete another tenant's files. The roots compared here are the
 * ones the stores use — a tenant on a shared AOS already has its AOS tenant id
 * subdirectory or prefix in it — so tenants sharing one AOS legitimately pass.
 *
 * Containment, not just equality: a tenant that keeps the base path (no AOS
 * tenant id) while another sits in a subdirectory of it would otherwise pass,
 * and the outer tenant's root then contains the inner one's — its recorded keys
 * resolve into the inner tenant's files and its retention sweep deletes from
 * them. */
function checkStorageIsolation(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const roots: Array<[string, string]> = []; // [tenant id, storage root]

  for (const [id, config] of tenants) {
    const {setting, root} = storageRoot(config);

    for (const [owner, existing] of roots) {
      const nested = root.startsWith(existing) || existing.startsWith(root);

      if (nested) {
        issues.push({
          path: tenantPath(id, ...setting),
          message:
            `Tenants "${owner}" ("${existing}") and "${id}" ("${root}") share ` +
            `a storage root — one contains the other. Give each tenant a ` +
            `directory or bucket of its own, or set ${name(tenantPath('<id>', 'aos', 'tenantId'))} ` +
            `on every tenant that shares one AOS instance.`,
        });
      }
    }

    roots.push([id, root]);
  }

  return issues;
}

/* Cross-tenant invariant. A tenant's signing key is what keeps its sessions its
 * own: a cookie is named for one tenant and opened with that tenant's key, so a
 * key belonging to one tenant alone is what makes a cookie of another tenant's
 * unreadable. Shared, the two tenants can open each other's sessions, and a
 * cookie renamed from one to the other is then accepted — read as the tenant its
 * payload names, which chooses the database, while the address chose the
 * instance. The session guard in lib/core/auth/server.ts refuses that mismatch; this refuses
 * the configuration that makes it reachable. */
function checkSecretIsolation(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const owners = new Map<string, string>();

  for (const [id, config] of tenants) {
    const secret = config.sessionSecret;
    const owner = owners.get(secret);

    if (owner) {
      issues.push({
        path: tenantPath(id, 'sessionSecret'),
        message:
          `Tenants "${owner}" and "${id}" share a session secret. Each tenant ` +
          `signs its own sessions, so a shared key lets either open the other's. ` +
          `Generate one per tenant with: openssl rand -base64 32`,
      });
    } else {
      owners.set(secret, id);
    }
  }

  return issues;
}

/* Cross-tenant invariant. Tenants sharing one mail account share one connection
 * pool, so they must agree on how many connections that account allows: the pool
 * is built by whichever tenant sends first, and a disagreement would make the
 * ceiling depend on send order — intermittently exceeding the limit the lower
 * value was set to respect. */
function checkMailCeilings(tenants: TenantEntry[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];
  const byAccount = new Map<string, {id: string; maxConnections: number}>();

  for (const [id, config] of tenants) {
    const mail = config.mail;
    if (!mail?.host) continue;

    const account = mailAccountKey(mail);
    const existing = byAccount.get(account);

    /* Compared as they are applied, not as they are written: leaving the setting
     * out means the default, so a tenant that omits it agrees with one that
     * spells that same number out. Refusing those would make an operator state
     * what the two configurations already mean. */
    const maxConnections = getMaxConnections(mail);

    if (existing && existing.maxConnections !== maxConnections) {
      issues.push({
        path: tenantPath(id, 'mail', 'maxConnections'),
        message:
          `Tenants "${existing.id}" and "${id}" share the mail account ` +
          `"${mail.user}" on ${mail.host} but allow it a different number of ` +
          `connections (${existing.maxConnections} and ${maxConnections}). ` +
          `They share one connection pool, so the ceiling must match — set ` +
          `${name(tenantPath('<id>', 'mail', 'maxConnections'))} to the same value for both.`,
      });
      continue;
    }

    if (!existing) {
      byAccount.set(account, {id, maxConnections});
    }
  }

  return issues;
}

/*
 * Checked against the tenants, because the two are configured separately.
 * Rename or drop a tenant and this can be left pointing at one that is not
 * there, and the addresses it serves answer not-found with no explanation.
 *
 * Required where a tenant is reached under a path segment, because such a
 * tenant sits on an origin whose own `/` serves no tenant: a visitor who types
 * the bare origin arrives at the deployment's entry, which has nothing to
 * resolve without this and answers not-found. `checkHostRouting` refuses a
 * path-routed tenant sharing a host with a host-routed one, so routing alone
 * never gives such an origin a tenant to answer its `/` — where this is
 * demanded, the unclaimed address is really there, and naming a tenant here is
 * what answers it.
 *
 * A deployment whose tenants are all reached by host is exempt. Its own origin
 * may still have an unanswered `/`, where no tenant holds that host, but that
 * is an infrastructure address — it carries `/deployment` and the sign-in
 * fallback, and a tenant address reached there is sent to the tenant's own
 * origin — so an operator is left to decide whether `/` on it leads anywhere
 * rather than made to hand it to one tenant of several.
 *
 * A single-tenant deployment declares nothing either way: one tenant is the
 * only answer, so the loader fills it in.
 *
 * A tenant that omits `routing` is path-routed, which is what the filter below
 * reads. A value that is neither spelling is refused by the property's own
 * type, which stops the configuration before this runs — unlike a failed
 * refinement, which arrives here with its value in place — so the routing seen
 * here is always one the tenant validly declared.
 */
function checkDefaultTenant(
  defaultTenant: string | undefined,
  tenants: TenantEntry[],
): ConfigIssue[] {
  const ids = tenants.map(([id]) => id);

  if (defaultTenant) {
    if (ids.includes(defaultTenant)) {
      return [];
    }

    return [
      {
        path: ['defaultTenant'],
        message:
          `"${defaultTenant}" names no configured tenant; the tenants are ` +
          `${ids.join(', ')}.`,
      },
    ];
  }

  if (ids.length < 2) {
    return [];
  }

  const pathRouted = tenants
    .filter(([, config]) => config.routing !== 'host')
    .map(([id]) => id);

  if (!pathRouted.length) {
    return [];
  }

  return [
    {
      path: ['defaultTenant'],
      message:
        `is required: ` +
        (pathRouted.length === 1
          ? `tenant "${pathRouted[0]}" is reached under a path segment, so ` +
            `"/" on the origin it is served on names no tenant.`
          : `tenants ${pathRouted.join(', ')} are reached under a path ` +
            `segment, so "/" on the origins they are served on names no ` +
            `tenant.`) +
        ` Name the tenant "/" leads to; the tenants are ${ids.join(', ')}.`,
    },
  ];
}

/* Cross-tenant invariant. The auth cookie names are settled once, as the auth
 * instance is built, from the scheme the deployment origin carries, so one
 * naming serves every origin in the configuration and the schemes have to
 * agree. Where they do not: an http tenant under an https deployment is sent
 * `__Secure-` cookies a browser refuses over http and holds no session at all,
 * and an https tenant under an http deployment is sent cookies carrying neither
 * the prefix nor the Secure attribute. Both are refused. */
function checkOriginSchemes(
  deploymentOrigin: unknown,
  tenants: TenantEntry[],
): ConfigIssue[] {
  const deployment = parseOrigin(deploymentOrigin);

  /* Nothing to compare the tenants against, and the setting's own check has
   * already reported why. Reporting a mismatch against a scheme that could not
   * be read would add a second fault to a configuration whose only fault is
   * this one. The tenants need no such guard: a tenant whose own origin was
   * refused does not reach here. */
  if (!deployment) return [];

  return tenants.flatMap(([id, config]) => {
    const declared = config.public.host;

    /* Null only in principle, for the reason above, but the type says it can be
     * and reading a scheme off it unchecked is what would throw. */
    const origin = parseOrigin(declared);

    if (!origin || origin.protocol === deployment.protocol) return [];

    return [
      {
        path: tenantPath(id, 'public', 'host'),
        message:
          `Tenant "${id}" is served on ${declared} while the deployment is ` +
          `served on ${deployment.origin}. Both have to use the same scheme — ` +
          `serve every origin over ${deployment.protocol.replace(':', '')}, or ` +
          `change ${name(['origin'])} to match.`,
      },
    ];
  });
}

/* Cross-tenant invariant. A host-routed tenant is named by the host it is served
 * on, so nothing else may be served on that host: the tenant segment is put back
 * on before the path is read, so whatever else was reached there has its own
 * first segment taken for one of this tenant's workspaces.
 *
 * Three claimants can collide on one host, and hosts are compared rather than
 * whole origins because a request carries no scheme to tell two apart:
 *
 * - another host-routed tenant, which leaves the host naming neither in
 *   particular;
 * - a path-routed tenant, whose own segment stops resolving;
 * - the addresses naming no tenant, where the default tenant says "/" leads
 *   somewhere other than the tenant holding that host.
 *
 * The last of those is refused only when the two disagree. A host-routed tenant
 * on the deployment origin's own host is the ordinary single-tenant deployment —
 * one tenant, holding every address of the origin it is served on, reached
 * without a tenant segment — and "/" leading to it is what an operator asked
 * for. It becomes a conflict only where the default tenant names a different
 * tenant, which is two answers to what "/" means on one host.
 *
 * Refused rather than resolved by an order of preference: a deployment where
 * which tenant answers depends on the order tenants happen to be declared in is
 * worse than one that will not start. */
function checkHostRouting(
  deploymentOrigin: unknown,
  defaultTenant: string | undefined,
  tenants: TenantEntry[],
): ConfigIssue[] {
  const issues: ConfigIssue[] = [];

  /* Keyed by `canonicalHost` — the spelling request routing compares with — so
   * what this refuses as claimed twice is exactly what would collide in the
   * routing index built from the same configuration. */
  const byHost = new Map<string, string>(); // host -> host-routed tenant id

  for (const [id, config] of tenants) {
    if (config.routing !== 'host') continue;

    const origin = parseOrigin(config.public.host);

    /* Null only in principle — a tenant whose own origin was refused does not
     * reach here — but reading a host off it unchecked is what would throw. */
    if (!origin) continue;

    const owner = byHost.get(canonicalHost(origin.host));

    if (owner) {
      issues.push({
        path: tenantPath(id, 'public', 'host'),
        message:
          `Tenants "${owner}" and "${id}" are both routed by host and both ` +
          `served on the host ${origin.host}, so a request arriving there names ` +
          `neither of them. Give each host-routed tenant a host of its own, or ` +
          `set ${name(tenantPath('<id>', 'routing'))} to path on one of them.`,
      });
      continue;
    }

    byHost.set(canonicalHost(origin.host), id);
  }

  for (const [id, config] of tenants) {
    if (config.routing === 'host') continue;

    const origin = parseOrigin(config.public.host);

    if (!origin) continue;

    const owner = byHost.get(canonicalHost(origin.host));

    if (owner) {
      issues.push({
        path: tenantPath(id, 'public', 'host'),
        message:
          `Tenant "${id}" is served on ${origin.origin} under a tenant path ` +
          `segment, but "${owner}" is routed by host on that same host, so ` +
          `/${id} there is read as one of "${owner}"'s workspaces. Serve "${id}" ` +
          `on another host, or route it by host too.`,
      });
    }
  }

  const deployment = parseOrigin(deploymentOrigin);
  const deploymentOwner =
    deployment && byHost.get(canonicalHost(deployment.host));

  if (deploymentOwner && defaultTenant && defaultTenant !== deploymentOwner) {
    issues.push({
      path: ['defaultTenant'],
      message:
        `"/" on ${deployment.origin} is claimed twice: "${deploymentOwner}" is ` +
        `routed by host there, so it answers every address of that origin, while ` +
        `${name(['defaultTenant'])} sends "/" to "${defaultTenant}". Name ` +
        `"${deploymentOwner}" there, or serve "${deploymentOwner}" on a host of ` +
        `its own. Leaving it unset works only where no tenant is reached under ` +
        `a path segment, which requires one.`,
    });
  }

  return issues;
}

function checkTenantIds(ids: string[]): ConfigIssue[] {
  const issues: ConfigIssue[] = [];

  for (const id of ids) {
    if (!TENANT_ID_PATTERN.test(id)) {
      issues.push({
        path: tenantPath(id),
        message:
          `"${id}" is not a usable tenant id. A tenant id is the URL path ` +
          `segment it is served under and the segment of every variable that ` +
          `configures it: a lowercase letter, then lowercase letters or digits.`,
      });
      continue;
    }

    if (isReservedSegment(id)) {
      issues.push({
        path: tenantPath(id),
        message:
          `"${id}" cannot be a tenant id: the deployment answers /${id} ` +
          `itself, so no request would reach a tenant named this. Reserved: ` +
          `${reservedSegments().join(', ')}.`,
      });
      continue;
    }

    if (id.length > TENANT_ID_MAX_LENGTH) {
      issues.push({
        path: tenantPath(id),
        message:
          `"${id}" is ${id.length} characters, and a tenant id may hold at ` +
          `most ${TENANT_ID_MAX_LENGTH}. A payment's reference ends with the ` +
          `tenant id, and Hub PISP carries the reference in a field of 35 ` +
          `characters, which leaves ${TENANT_ID_MAX_LENGTH} for the id.`,
      });
    }
  }

  return issues;
}

/*
 * The whole configuration: the deployment's settings, plus one entry per tenant
 * under `tenants`, keyed by tenant id.
 *
 * The tenant ids are a record's keys rather than declared properties, which is
 * what lets an operator name their own tenants; the load enforces what an id may
 * be below, where the message can say what an id is for.
 */
export const configSchema = z
  .strictObject({
    ...deploymentConfigSchema.shape,
    [TENANTS_KEY]: z.record(z.string(), tenantConfigSchema),
  })
  /* These see a configuration that parsed — a setting of the wrong type, a
   * missing one, or a name no group declares stops the parse before this — but
   * not one every setting accepted. A failed refinement leaves its value in
   * place and the configuration still arrives here, so a check can read a
   * setting a refinement has just rejected; and a transform behind a failed
   * refinement has not run, so a value can arrive neither as written nor as the
   * application would use it. A tenant whose storage settings were refused is
   * the case that occurs: its storage arrives as the flat group an operator
   * wrote rather than settled into the one provider's shape the application
   * reads, and a check reading the provider's settings off it finds nothing.
   *
   * So the checks comparing tenants against each other are given only the
   * tenants whose own settings reported nothing. Comparing against a value that
   * is not the one the application will use reports a collision against
   * whichever tenant is configured correctly, sending an operator to change
   * the entry that is already right. A collision that a skipped tenant is
   * genuinely part of is reported once its own fault is fixed. */
  .check(ctx => {
    const tenants = Object.entries(ctx.value[TENANTS_KEY]) as TenantEntry[];

    const ids = tenants.map(([id]) => id);

    /* Every issue raised so far carries the path it belongs to, and a tenant's
     * id is the second segment of a path under `tenants`. */
    const faulted = new Set(
      ctx.issues
        .filter(issue => issue.path?.[0] === TENANTS_KEY)
        .map(issue => issue.path?.[1])
        .filter((segment): segment is string => typeof segment === 'string'),
    );

    const settled = tenants.filter(([id]) => !faulted.has(id));

    const issues = [
      /* Every id, faulted or not: the key is the name, whatever the entry under
       * it holds. */
      ...checkTenantIds(ids),
      ...(tenants.length
        ? [
            /* The tenants whole, not `settled`: what a tenant is named, and
             * how it is routed, is answered by its own entry however the rest
             * of that entry fared. */
            ...checkDefaultTenant(ctx.value.defaultTenant, tenants),
            ...checkOriginSchemes(ctx.value.origin, settled),
            ...checkHostRouting(
              ctx.value.origin,
              ctx.value.defaultTenant,
              settled,
            ),
            ...checkHubPispCertIsolation(settled),
            ...checkSecretIsolation(settled),
            ...checkStorageIsolation(settled),
            ...checkMailCeilings(settled),
          ]
        : [
            {
              path: [TENANTS_KEY],
              message:
                `No tenant is configured. Every tenant is declared by its ` +
                `variables, ${name([TENANTS_KEY, '<id>'])}_…; see env.example.`,
            },
          ]),
    ];

    for (const issue of issues) {
      ctx.issues.push({
        code: 'custom',
        input: ctx.value,
        path: issue.path,
        message: issue.message,
      });
    }
  });

export type Config = z.output<typeof configSchema>;
export type ConfigInput = z.input<typeof configSchema>;
